apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tacokumo

resources:
  - deployment.yaml
  - service.yaml
  - secret.yaml
  - ingress.yaml
  - hpa.yaml

commonLabels:
  app: admin-ui
  managed-by: kustomize

images:
  - name: admin-ui
    newName: your-registry/admin-ui
    newTag: latest
